name: 'deploy to staging'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy-to-staging:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: npm

      - name: install
        run: npm ci

      - name: trigger staging deploy
        env:
          SEED_TOKEN: ${{ secrets.SEED_TOKEN }}
        run: npx seed deploy --org sourcierltd --app friendly-broccoli --stage staging --commit ${{ github.sha }}
